"""
dynamic_dag_factory — Dynamic DAG generation reference example.

See: 09-composer-migration/03-dynamic-dag-generation.md

Generates one DAG per entry in JOB_FAMILY_CONFIG, for a family of
structurally identical "standard batch" jobs: ephemeral cluster created,
one Spark job submitted, cluster deleted. Config-driven differences are
schedule, data domain, and resource tier only — anything needing more
divergence than this should be a hand-written DAG instead (see
03-dynamic-dag-generation.md "When to use dynamic generation").
"""

from datetime import datetime, timedelta
from typing import Any, Dict, List

from airflow import DAG
from airflow.providers.google.cloud.operators.dataproc import (
    DataprocCreateClusterOperator,
    DataprocDeleteClusterOperator,
    DataprocSubmitJobOperator,
)

from dags.common.alerting import alert_on_task_failure
from dags.common.cluster_configs import get_cluster_config_for_tier

# Sourced from / kept in lockstep with 01-discovery/inventories/06-job-inventory.md.
# In a real deployment this list is generated from a checked-in YAML file,
# not hand-maintained inline here.
JOB_FAMILY_CONFIG: List[Dict[str, Any]] = [
    {
        "job_name": "merchandising_weekly_report",
        "data_domain": "merchandising",
        "schedule_interval": "0 6 * * 1",
        "tier": 3,
        "sla_hours": 24,
    },
    {
        "job_name": "marketing_campaign_attribution",
        "data_domain": "marketing",
        "schedule_interval": "0 2 * * *",
        "tier": 2,
        "sla_hours": 6,
    },
    {
        "job_name": "finance_gl_reconciliation",
        "data_domain": "finance",
        "schedule_interval": "0 5 1 * *",
        "tier": 1,
        "sla_hours": 5,
    },
]

PROJECT_ID = "{{ var.value.gcp_project_id }}"
REGION = "{{ var.value.gcp_region }}"
ARTIFACT_BUCKET = "{{ var.value.artifact_bucket }}"


def build_standard_batch_dag(job_config: Dict[str, Any]) -> DAG:
    """
    Builds one standard-shaped batch DAG from a job_config entry.

    Kept deliberately simple and heavily unit-tested (see the shared
    library test coverage standard in 07-spark-migration/09-unit-testing-strategy.md)
    since a bug here affects every DAG generated by this factory.
    """
    job_name = job_config["job_name"]
    data_domain = job_config["data_domain"]
    tier = job_config["tier"]
    cluster_name = f"{job_name.replace('_', '-')}-{{{{ ds_nodash }}}}"

    default_args = {
        "owner": f"data-engineering-{data_domain}",
        "retries": {1: 3, 2: 2, 3: 1}[tier],
        "retry_delay": timedelta(minutes={1: 5, 2: 10, 3: 15}[tier]),
        "on_failure_callback": alert_on_task_failure,
        "sla": timedelta(hours=job_config["sla_hours"]),
        "start_date": datetime(2026, 1, 1),
        "params": {"tier": tier},
    }

    with DAG(
        dag_id=f"{data_domain}_{job_name}",
        schedule_interval=job_config["schedule_interval"],
        default_args=default_args,
        catchup=False,
        tags=[data_domain, f"tier-{tier}", "batch", "dynamically-generated"],
    ) as dag:

        create_cluster = DataprocCreateClusterOperator(
            task_id="create_cluster",
            project_id=PROJECT_ID,
            region=REGION,
            cluster_name=cluster_name,
            cluster_config=get_cluster_config_for_tier(tier),
        )

        submit_job = DataprocSubmitJobOperator(
            task_id=f"submit_{job_name}",
            project_id=PROJECT_ID,
            region=REGION,
            job={
                "reference": {"job_id": f"{job_name}-{{{{ ds_nodash }}}}"},
                "placement": {"cluster_name": cluster_name},
                "pyspark_job": {
                    "main_python_file_uri": (
                        f"gs://{ARTIFACT_BUCKET}/jobs/{job_name.replace('_', '-')}/"
                        f"{{{{ var.value.{job_name}_version }}}}/main.py"
                    ),
                    "python_file_uris": [
                        f"gs://{ARTIFACT_BUCKET}/libs/dp-spark-common-"
                        f"{{{{ var.value.common_lib_version }}}}.zip"
                    ],
                    "args": ["--env", "{{ var.value.environment }}", "--run-date", "{{ ds }}"],
                },
            },
        )

        delete_cluster = DataprocDeleteClusterOperator(
            task_id="delete_cluster",
            project_id=PROJECT_ID,
            region=REGION,
            cluster_name=cluster_name,
            trigger_rule="all_done",
        )

        create_cluster >> submit_job >> delete_cluster

    return dag


# Airflow discovers DAGs via module-level globals — this is the standard,
# documented way to register dynamically generated DAGs.
for _job_config in JOB_FAMILY_CONFIG:
    _dag = build_standard_batch_dag(_job_config)
    globals()[f"{_job_config['data_domain']}_{_job_config['job_name']}"] = _dag
